"""initial tables

Revision ID: 411e0de3bc57
Revises: 
Create Date: 2026-09-28 03:32:04.101961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411e0de3bc57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('seed', sa.String(length=120), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('ruleset', sa.JSON(), nullable=True),
    sa.Column('environment_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_world_tick', ['world_id', 'tick'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.Column('scenario', sa.String(length=120), nullable=False),
    sa.Column('seed', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_configuration', sa.JSON(), nullable=True),
    sa.Column('compute_budget', sa.JSON(), nullable=True),
    sa.Column('generation_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('populations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('root_agent_id', sa.Integer(), nullable=True),
    sa.Column('population_rules', sa.JSON(), nullable=True),
    sa.Column('model_configuration', sa.JSON(), nullable=True),
    sa.Column('resource_limits', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('birth_tick', sa.Integer(), nullable=True),
    sa.Column('death_tick', sa.Integer(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('inherited_traits', sa.JSON(), nullable=True),
    sa.Column('inherited_knowledge', sa.JSON(), nullable=True),
    sa.Column('acquired_knowledge', sa.JSON(), nullable=True),
    sa.Column('working_memory', sa.JSON(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('compute_budget', sa.JSON(), nullable=True),
    sa.Column('remaining_budget', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents')
    op.drop_table('populations')
    op.drop_table('experiments')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_world_tick')

    op.drop_table('events')
    op.drop_table('worlds')
    # ### end Alembic commands ###
